#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.IO.DataAccess.Transactions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TransactionDB")]
	public partial class TransactionDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TransactionDBDataContext() : 
				base(global::Cloud.IO.DataAccess.Properties.Settings.Default.TransactionDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TransactionDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransactionDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransactionDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransactionDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LogRegister")]
		public int LogRegister([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string appName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string logTracce, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(20)")] string actionType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string content)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), appName, dateTime, userID, logTracce, action, actionType, content);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
