<?xml version="1.0" encoding="utf-8"?><Database Name="TransactionDB" Class="DataManageDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.18.23.229\EXPSQL2008R2;Initial Catalog=TransactionDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TransactionDBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.getLServiceList" Method="getLServiceList">
    <ElementType Name="getLServiceListResult">
      <Column Name="Service_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetServiceByName" Method="GetServiceByName">
    <Parameter Name="serviceName" Type="System.String" DbType="VarChar(70)" />
    <ElementType Name="GetServiceByNameResult">
      <Column Name="Service_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTransactionBasedOnUserID" Method="GetTransactionBasedOnUserID">
    <Parameter Name="userID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetTransactionBasedOnUserIDResult">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[DESC]" Member="DESC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RegisterNewService" Method="RegisterNewService">
    <Parameter Name="serviceName" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="url" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TransactionAdd" Method="TransactionAdd">
    <Parameter Name="userID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="departure" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="destination" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="method" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="dateTime" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="content" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LogRegister" Method="LogRegister">
    <Parameter Name="appName" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="dateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="logTracce" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="action" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="actionType" Type="System.String" DbType="Char(20)" />
    <Parameter Name="content" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
</Database>