//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageServer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GateWayService1Soap")]
    public interface GateWayService1Soap {
        
        // CODEGEN: Generating message contract since element name AppName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute_Method", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageServer.ServiceReference1.ArrayOfAnyType))]
        MessageServer.ServiceReference1.Execute_MethodResponse Execute_Method(MessageServer.ServiceReference1.Execute_MethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Execute_Method", ReplyAction="*")]
        System.Threading.Tasks.Task<MessageServer.ServiceReference1.Execute_MethodResponse> Execute_MethodAsync(MessageServer.ServiceReference1.Execute_MethodRequest request);
        
        // CODEGEN: Generating message contract since element name AppName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloudService_ExecuteMethod", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageServer.ServiceReference1.ArrayOfAnyType))]
        MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse CloudService_ExecuteMethod(MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloudService_ExecuteMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse> CloudService_ExecuteMethodAsync(MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_MethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute_Method", Namespace="http://tempuri.org/", Order=0)]
        public MessageServer.ServiceReference1.Execute_MethodRequestBody Body;
        
        public Execute_MethodRequest() {
        }
        
        public Execute_MethodRequest(MessageServer.ServiceReference1.Execute_MethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Execute_MethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClassName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MethodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MessageServer.ServiceReference1.ArrayOfAnyType Params;
        
        public Execute_MethodRequestBody() {
        }
        
        public Execute_MethodRequestBody(string AppName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            this.AppName = AppName;
            this.ClassName = ClassName;
            this.MethodName = MethodName;
            this.Params = Params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute_MethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute_MethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public MessageServer.ServiceReference1.Execute_MethodResponseBody Body;
        
        public Execute_MethodResponse() {
        }
        
        public Execute_MethodResponse(MessageServer.ServiceReference1.Execute_MethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Execute_MethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object Execute_MethodResult;
        
        public Execute_MethodResponseBody() {
        }
        
        public Execute_MethodResponseBody(object Execute_MethodResult) {
            this.Execute_MethodResult = Execute_MethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloudService_ExecuteMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloudService_ExecuteMethod", Namespace="http://tempuri.org/", Order=0)]
        public MessageServer.ServiceReference1.CloudService_ExecuteMethodRequestBody Body;
        
        public CloudService_ExecuteMethodRequest() {
        }
        
        public CloudService_ExecuteMethodRequest(MessageServer.ServiceReference1.CloudService_ExecuteMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CloudService_ExecuteMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ServiceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClassName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MethodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MessageServer.ServiceReference1.ArrayOfAnyType Params;
        
        public CloudService_ExecuteMethodRequestBody() {
        }
        
        public CloudService_ExecuteMethodRequestBody(string AppName, string ServiceName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            this.AppName = AppName;
            this.ServiceName = ServiceName;
            this.ClassName = ClassName;
            this.MethodName = MethodName;
            this.Params = Params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloudService_ExecuteMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloudService_ExecuteMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public MessageServer.ServiceReference1.CloudService_ExecuteMethodResponseBody Body;
        
        public CloudService_ExecuteMethodResponse() {
        }
        
        public CloudService_ExecuteMethodResponse(MessageServer.ServiceReference1.CloudService_ExecuteMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CloudService_ExecuteMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object CloudService_ExecuteMethodResult;
        
        public CloudService_ExecuteMethodResponseBody() {
        }
        
        public CloudService_ExecuteMethodResponseBody(object CloudService_ExecuteMethodResult) {
            this.CloudService_ExecuteMethodResult = CloudService_ExecuteMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GateWayService1SoapChannel : MessageServer.ServiceReference1.GateWayService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GateWayService1SoapClient : System.ServiceModel.ClientBase<MessageServer.ServiceReference1.GateWayService1Soap>, MessageServer.ServiceReference1.GateWayService1Soap {
        
        public GateWayService1SoapClient() {
        }
        
        public GateWayService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateWayService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServer.ServiceReference1.Execute_MethodResponse MessageServer.ServiceReference1.GateWayService1Soap.Execute_Method(MessageServer.ServiceReference1.Execute_MethodRequest request) {
            return base.Channel.Execute_Method(request);
        }
        
        public object Execute_Method(string AppName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            MessageServer.ServiceReference1.Execute_MethodRequest inValue = new MessageServer.ServiceReference1.Execute_MethodRequest();
            inValue.Body = new MessageServer.ServiceReference1.Execute_MethodRequestBody();
            inValue.Body.AppName = AppName;
            inValue.Body.ClassName = ClassName;
            inValue.Body.MethodName = MethodName;
            inValue.Body.Params = Params;
            MessageServer.ServiceReference1.Execute_MethodResponse retVal = ((MessageServer.ServiceReference1.GateWayService1Soap)(this)).Execute_Method(inValue);
            return retVal.Body.Execute_MethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServer.ServiceReference1.Execute_MethodResponse> MessageServer.ServiceReference1.GateWayService1Soap.Execute_MethodAsync(MessageServer.ServiceReference1.Execute_MethodRequest request) {
            return base.Channel.Execute_MethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServer.ServiceReference1.Execute_MethodResponse> Execute_MethodAsync(string AppName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            MessageServer.ServiceReference1.Execute_MethodRequest inValue = new MessageServer.ServiceReference1.Execute_MethodRequest();
            inValue.Body = new MessageServer.ServiceReference1.Execute_MethodRequestBody();
            inValue.Body.AppName = AppName;
            inValue.Body.ClassName = ClassName;
            inValue.Body.MethodName = MethodName;
            inValue.Body.Params = Params;
            return ((MessageServer.ServiceReference1.GateWayService1Soap)(this)).Execute_MethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse MessageServer.ServiceReference1.GateWayService1Soap.CloudService_ExecuteMethod(MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest request) {
            return base.Channel.CloudService_ExecuteMethod(request);
        }
        
        public object CloudService_ExecuteMethod(string AppName, string ServiceName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest inValue = new MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest();
            inValue.Body = new MessageServer.ServiceReference1.CloudService_ExecuteMethodRequestBody();
            inValue.Body.AppName = AppName;
            inValue.Body.ServiceName = ServiceName;
            inValue.Body.ClassName = ClassName;
            inValue.Body.MethodName = MethodName;
            inValue.Body.Params = Params;
            MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse retVal = ((MessageServer.ServiceReference1.GateWayService1Soap)(this)).CloudService_ExecuteMethod(inValue);
            return retVal.Body.CloudService_ExecuteMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse> MessageServer.ServiceReference1.GateWayService1Soap.CloudService_ExecuteMethodAsync(MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest request) {
            return base.Channel.CloudService_ExecuteMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageServer.ServiceReference1.CloudService_ExecuteMethodResponse> CloudService_ExecuteMethodAsync(string AppName, string ServiceName, string ClassName, string MethodName, MessageServer.ServiceReference1.ArrayOfAnyType Params) {
            MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest inValue = new MessageServer.ServiceReference1.CloudService_ExecuteMethodRequest();
            inValue.Body = new MessageServer.ServiceReference1.CloudService_ExecuteMethodRequestBody();
            inValue.Body.AppName = AppName;
            inValue.Body.ServiceName = ServiceName;
            inValue.Body.ClassName = ClassName;
            inValue.Body.MethodName = MethodName;
            inValue.Body.Params = Params;
            return ((MessageServer.ServiceReference1.GateWayService1Soap)(this)).CloudService_ExecuteMethodAsync(inValue);
        }
    }
}
