//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.IU.WEB.APIManagementCenter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIManagementCenter.IAPIManagementService")]
    public interface IAPIManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIManagementService/ExecuteMethod", ReplyAction="http://tempuri.org/IAPIManagementService/ExecuteMethodResponse")]
        object ExecuteMethod();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIManagementService/ExecuteMethod", ReplyAction="http://tempuri.org/IAPIManagementService/ExecuteMethodResponse")]
        System.Threading.Tasks.Task<object> ExecuteMethodAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIManagementServiceChannel : Cloud.IU.WEB.APIManagementCenter.IAPIManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIManagementServiceClient : System.ServiceModel.ClientBase<Cloud.IU.WEB.APIManagementCenter.IAPIManagementService>, Cloud.IU.WEB.APIManagementCenter.IAPIManagementService {
        
        public APIManagementServiceClient() {
        }
        
        public APIManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object ExecuteMethod() {
            return base.Channel.ExecuteMethod();
        }
        
        public System.Threading.Tasks.Task<object> ExecuteMethodAsync() {
            return base.Channel.ExecuteMethodAsync();
        }
    }
}
